name: Android Testflight
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Name of the branch"
        required: false
        default: ""

jobs:
  build-and-release:
    runs-on: macos-26
    steps:
      - name: üõ†Ô∏è Checkout repository
        uses: actions/checkout@v4
        with:
            repository: saltpi/iPlay.Android
            ref: 'develop'
            submodules: recursive
            fetch-depth: 0

      - name: ‚òïÔ∏è set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '21'
            distribution: 'zulu'
            cache: gradle

      - name: üß¨ Build
        env:
          scheme: ${{ 'default' }}
        run: |
          make all
          
      # - name: ‚òÅÔ∏è Upload to Onedrive
      #   run: |
      #     version_code="$(git rev-list --count HEAD)"
      #     buildtime=$(date '+%Y%m%d.%H%M')
      #     wget https://drive.ourfor.top/tools/upload_session.py -O upload.py
      #     python -m pip install requests tqdm
      #     python upload.py --url "https://drive.ourfor.top/od_bot/build/iPlay/Android/iPlay_arm64_v8a_build_${version_code}.apk" \
      #       --file "$PWD/build/iPlay-arm64-v8a.apk" \
      #       --token "${{ secrets.ONEDRIVE_CLIENT_ID }}"
      #     echo "https://drive.ourfor.top/od_bot/build/iPlay/Android/iPlay_arm64_v8a_build_${version_code}.apk" > "$PWD/latest.apk.url"
      #     python upload.py --url "https://drive.ourfor.top/od_bot/build/iPlay/Android/latest.apk.url" \
      #       --file "$PWD/latest.apk.url" \
      #       --token "${{ secrets.ONEDRIVE_CLIENT_ID }}"
      #   shell: bash
      - name: üî¢ Update Build Number
        id: update_build_number
        run: |
          version_code="$(git rev-list --count HEAD)"
          buildtime=$(date '+%Y%m%d.%H%M')
          echo "version_code=$version_code" >> $GITHUB_OUTPUT
          echo "buildtime=$buildtime" >> $GITHUB_OUTPUT

      - name: üè∑Ô∏è Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          repository: endpne/iPlay-Release-Android
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          name: Android Build ${{ steps.update_build_number.outputs.version_code }}
          tag_name: android-build-${{ steps.update_build_number.outputs.version_code }}
          make_latest: true
          body: |
            Android TestFlight Build
            
            Build artifacts:
            - iPlay.apk (TestFlight package)
            
            **Installation Options:**
            1. Use the .apk file for TestFlight distribution
          files: |
            build/iPlay-arm64-v8a.apk
